export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS"
export const GET_POKE_DETAIL = "GET_POKE_DETAIL"
export const CLEAN_DETAIL = "CLEAN_DETAIL"
export const CREATE_POKEMON = "CREATE_POKEMON"
export const SEARCH_POKEMON = "SEARCH_POKEMON"
export const FILTER_POKEMON = "FILTER_POKEMON"
export const FILTER_TYPE_POKEMON = "FILTER_TYPE_POKEMON"
export const ORDER_POKEMON = "ORDER_POKEMON"
export const GET_TYPES = "GET_TYPES"
 

